### ISSUE TITLE
Error in simhub log

### ISSUE THREAD

**Issue by ilduca1960** [ducng99/SimHub-to-F12020-UDP#6]
Dear, first of all thanks alot for your job!
I have this error in the log of Simhub

Failed to send UDP packet<br>System.MissingMethodException: Method not found: 'SimHub.Plugins.PluginManager SimHub.Plugins.PluginManager.GetInstance()'.<br> &nbsp;&nbsp;at SimHubToF12020UDP.Packets.CarStatusDataPacket.Read()<br> &nbsp;&nbsp;at SimHubToF12020UDPPlugin.UDPServer.&lt;LoopCarStatusData&gt;d__15.MoveNext()</TD></TR><

couid you help?

**Comment by ilduca1960** [comment]
now I installed last version of Simhub and I can establisg the connectin. The display on the SF1000 shows the dashboard but no dynamic data is shown. The log reports these errors

[2023-03-22 22:17:36,329] ERROR - Failed to send UDP packet
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at SimHubToF12020UDP.Utils.ClampFloatingValue[T](Object value)
   at SimHubToF12020UDP.Packets.LapDataPacket.Read()
   at SimHubToF12020UDPPlugin.UDPServer.<LoopLapData>d__16.MoveNext()
[2023-03-22 22:17:36,329] ERROR - Failed to send UDP packet
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at SimHubToF12020UDP.Utils.ClampFloatingValue[T](Object value)
   at SimHubToF12020UDP.Packets.CarTelemetryDataPacket.Read()
   at SimHubToF12020UDPPlugin.UDPServer.<LoopCarTelemetryData>d__14.MoveNext()
[2023-03-22 22:17:36,329] ERROR - Failed to send UDP packet
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at SimHubToF12020UDP.Utils.ClampFloatingValue[T](Object value)
   at SimHubToF12020UDP.Packets.CarStatusDataPacket.Read()
   at SimHubToF12020UDPPlugin.UDPServer.<LoopCarStatusData>d__15.MoveNext()
[2023-03-22 22:17:36,359] ERROR - Failed to send UDP packet
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at SimHubToF12020UDP.Utils.ClampFloatingValue[T](Object value)
   at SimHubToF12020UDP.Packets.LapDataPacket.Read()
   at SimHubToF12020UDPPlugin.UDPServer.<LoopLapData>d__16.MoveNext()
[2023-03-22 22:17:36,359] ERROR - Failed to send UDP packet
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at SimHubToF12020UDP.Utils.ClampFloatingValue[T](Object value)
   at SimHubToF12020UDP.Packets.CarStatusDataPacket.Read()
   at SimHubToF12020UDPPlugin.UDPServer.<LoopCarStatusData>d__15.MoveNext()

**Comment by ilduca1960** [comment]
Fixed. I loaded previous version [v1.1.0](https://github.com/ducng99/SimHub-to-F12020-UDP/releases/tag/v1.1.0) and now is working.

just some more feedback to improve:
1 ERS level is not showed
2. Button ERS when pressed is nt showing ERS activated on the display

thanks!!!

**Comment by ducng99** [comment]
Hi @ilduca1960, I will have a look into this and thanks for the logs!

**Comment by ducng99** [comment]
I've released v1.1.2 which should fix the overflow issue

Re. your suggestion 
1. I am looking into this right now, if I remember correctly, SimHub didn't provide enough info - but looks like it is now!
2. "ERS active" state is not reported by SimHub, I cannot implement this as it goes against my goal of not using any other plugins. With that said, I can look at optionally supporting this if another plugin is installed.

**Comment by ducng99** [comment]
Yeah, I tried AC with RSS cars but ERS values are all over the place unfortunately.

But glad you are find this plugin helpful! Thanks 👍

**Comment by ilduca1960** [comment]
Hi @ducng99 Imade some searc inside Simhub dashes and I found these information:

In the gauge showing the current level of Kers charge
if(isnull([DataCorePlugin.GameRawData.StaticInfo.HasKERS],0) or isnull([DataCorePlugin.GameRawData.StaticInfo.HasERS],0),isnull([DataCorePlugin.GameRawData.Physics.KersCharge],1),1)

Range 0.000000 upto 1


In the gauge showing the current ERS use in the Lap
isnull([DataCorePlugin.GameRawData.Physics.KersCurrentKJ],0)      

value from 0 to ErsMax


Max value ERS permitterd per Lap
isnull([DataCorePlugin.GameRawData.StaticInfo.ErsMaxJ],0)/1000     

Value noted is 8000


I don't know if this help you to implement something more, for me the ERS info is important when I drive AC with F1 or LMP cars. I suppose that the SF1000 display has surely this information showed in some dash for F1

Thanks anyhow for trying
Claudio
